version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: ufc_fighter_stats/api/app.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: postgres://postgres:1234@db:5432/ufc_fighter_data
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ufc_fighter_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
