import unittest
import os
import sys

# Append the parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Now you can import scrape_fighter_data from scrape.py
from scrapping.scrape import scrape_fighter_data
class TestScrapingUrls(unittest.TestCase):
    def test_full_details(self):
        self.assertEqual(scrape_fighter_data("https://www.ufc.com/athlete/sean-omalley"), {'name': "Sean O'Malley", 'division_title': 'Bantamweight Division', 'win': 18, 'loss': 1, 'draw': 0, 'trains_at': 'MMA LAB - Glendale, AZ', 'place_of_birth': 'Helena, United States', 'status': 'Active', 'fight_style': None, 'age': 29, 'height': '71.00', 'weight': '135.00', 'ufc_debut': 'Jul. 18, 2017', 'reach': '72.00', 'leg_reach': '40.00', 'wins_by_knockout': 12, 'first_round_finishes': 9, 'striking_accuracy_percent': 62.0, 'significant_strikes_landed': 991, 'significant_strikes_attempted': 1601, 'takedown_accuracy_percent': 43.0, 'takedowns_landed': 3, 'takedowns_attempted': 7, 'sig_str_landed_per_min': 7.63, 'sig_str_absorbed_per_min': 3.52, 'takedown_avg_per_15_min': 0.35, 'submission_avg_per_15_min': 0.35, 'sig_str_defense_percent': 62.0, 'takedown_defense_percent': 63.0, 'knockdown_avg': 0.92, 'average_fight_time': '10:00', 'sig_str_standing_amount': 935, 'sig_str_clinch_amount': 21, 'sig_str_ground_amount': 35, 'win_by_ko_tko_amount': 12, 'win_by_dec_amount': 5, 'win_by_sub_amount': 1, 'sig_str_standing_percentage': 94.0, 'sig_str_clinch_percentage': 2.0, 'sig_str_ground_percentage': 4.0, 'win_by_ko_tko_percentage': 67.0, 'win_by_dec_percentage': 28.0, 'win_by_sub_percentage': 6.0, 'strike_to_head': 691, 'strike_to_head_per': 70.0, 'strike_to_body': 212, 'strike_to_body_per': 21.0, 'strike_to_leg': 88, 'strike_to_leg_per': 9.0})
    #Sean O Malley has all the details and stats filled up

    def test_some_details_missing(self):
        self.assertEqual(scrape_fighter_data("https://www.ufc.com/athlete/hamdy-abdelwahab"), {'name': 'Hamdy Abdelwahab', 'division_title': 'Heavyweight Division', 'win': 5, 'loss': 0, 'draw': 0, 'trains_at': None, 'place_of_birth': 'Egypt', 'status': 'Active', 'fight_style': 'Wrestler', 'age': 30, 'height': '74.00', 'weight': '264.50', 'ufc_debut': 'Jul. 30, 2022', 'reach': '72.00', 'leg_reach': '41.00', 'wins_by_knockout': 5, 'first_round_finishes': 4, 'striking_accuracy_percent': 53.0, 'significant_strikes_landed': 58, 'significant_strikes_attempted': 110, 'takedown_accuracy_percent': 75.0, 'takedowns_landed': 3, 'takedowns_attempted': 4, 'sig_str_landed_per_min': 3.87, 'sig_str_absorbed_per_min': None, 'takedown_avg_per_15_min': 3.0, 'submission_avg_per_15_min': None, 'sig_str_defense_percent': 59.0, 'takedown_defense_percent': None, 'knockdown_avg': 1.0, 'average_fight_time': None, 'sig_str_standing_amount': 30, 'sig_str_clinch_amount': 2, 'sig_str_ground_amount': 26, 'win_by_ko_tko_amount': 5, 'win_by_dec_amount': 0, 'win_by_sub_amount': 0, 'sig_str_standing_percentage': 52.0, 'sig_str_clinch_percentage': 3.0, 'sig_str_ground_percentage': 45.0, 'win_by_ko_tko_percentage': 100.0, 'win_by_dec_percentage': 0.0, 'win_by_sub_percentage': 0.0, 'strike_to_head': 51, 'strike_to_head_per': 88.0, 'strike_to_body': 5, 'strike_to_body_per': 9.0, 'strike_to_leg': 2, 'strike_to_leg_per': 3.0})
    #Hamdy Abdelwahab have his trains at not available in the website

    def test_some_details_blank(self):
        self.assertEqual(scrape_fighter_data("https://www.ufc.com/athlete/israel-adesanya"), {'name': 'Israel Adesanya', 'division_title': 'Middleweight Division', 'win': 24, 'loss': 3, 'draw': 0, 'trains_at': 'City Kickboxing', 'place_of_birth': 'Lagos, Nigeria', 'status': 'Active', 'fight_style': 'Freestyle', 'age': 34, 'height': '76.00', 'weight': '184.80', 'ufc_debut': 'Feb. 11, 2018', 'reach': '80.00', 'leg_reach': '44.50', 'wins_by_knockout': 16, 'first_round_finishes': 6, 'striking_accuracy_percent': 48.0, 'significant_strikes_landed': 1148, 'significant_strikes_attempted': 2386, 'takedown_accuracy_percent': 14.0, 'takedowns_landed': None, 'takedowns_attempted': 7, 'sig_str_landed_per_min': 3.93, 'sig_str_absorbed_per_min': 3.11, 'takedown_avg_per_15_min': 0.05, 'submission_avg_per_15_min': 0.15, 'sig_str_defense_percent': 56.0, 'takedown_defense_percent': 78.0, 'knockdown_avg': 0.67, 'average_fight_time': '18:16', 'sig_str_standing_amount': 1052, 'sig_str_clinch_amount': 60, 'sig_str_ground_amount': 36, 'win_by_ko_tko_amount': 16, 'win_by_dec_amount': 7, 'win_by_sub_amount': 0, 'sig_str_standing_percentage': 92.0, 'sig_str_clinch_percentage': 5.0, 'sig_str_ground_percentage': 3.0, 'win_by_ko_tko_percentage': 70.0, 'win_by_dec_percentage': 30.0, 'win_by_sub_percentage': 0.0, 'strike_to_head': 551, 'strike_to_head_per': 48.0, 'strike_to_body': 234, 'strike_to_body_per': 20.0, 'strike_to_leg': 363, 'strike_to_leg_per': 32.0})
    #Israel Adesanya has leg takedowns in blank due to a glitch in the website

    def test_most_details_missing(self):
        self.assertEqual(scrape_fighter_data("https://www.ufc.com/athlete/danny-abbadi"), {'name': 'Danny Abbadi', 'division_title': 'Lightweight Division', 'win': 2, 'loss': 2, 'draw': 0, 'trains_at': None, 'place_of_birth': 'Orlando, United States', 'status': 'Not Fighting', 'fight_style': None, 'age': 39, 'height': '71.00', 'weight': '156.00', 'ufc_debut': 'Jun. 24, 2006', 'reach': None, 'leg_reach': None, 'wins_by_knockout': None, 'first_round_finishes': None, 'striking_accuracy_percent': 38.0, 'significant_strikes_landed': 59, 'significant_strikes_attempted': 155, 'takedown_accuracy_percent': None, 'takedowns_landed': None, 'takedowns_attempted': None, 'sig_str_landed_per_min': 3.29, 'sig_str_absorbed_per_min': 4.41, 'takedown_avg_per_15_min': 0.0, 'submission_avg_per_15_min': 0.0, 'sig_str_defense_percent': 58.0, 'takedown_defense_percent': 78.0, 'knockdown_avg': 0.0, 'average_fight_time': '08:58', 'sig_str_standing_amount': 42, 'sig_str_clinch_amount': 14, 'sig_str_ground_amount': 3, 'win_by_ko_tko_amount': None, 'win_by_dec_amount': None, 'win_by_sub_amount': None, 'sig_str_standing_percentage': 71.0, 'sig_str_clinch_percentage': 24.0, 'sig_str_ground_percentage': 5.0, 'win_by_ko_tko_percentage': None, 'win_by_dec_percentage': None, 'win_by_sub_percentage': None, 'strike_to_head': 51, 'strike_to_head_per': 86.0, 'strike_to_body': 8, 'strike_to_body_per': 14.0, 'strike_to_leg': 0, 'strike_to_leg_per': 0.0})
    #Danny Abbadi has many details unavailable such as his takedown stats and also a lot of information from his biography section

if __name__ == '__main__':
    unittest.main()
    